export default {
  notfound: "/assets/images/404.svg",
  logo: "/vercel.svg",
  logo_img:"/assets/images/logo.png",
  socialicnone:"/assets/images/twittericn01.svg",
  socialicntwo:"/assets/images/facebookicn01.svg",
  socialicnthree:"/assets/images/youtubeicn01.svg",
  socialicnfour:"/assets/images/instagramicn01.svg",
  noimage:"/assets/images/logo.png",
  menu_icon:"/assets/images/menu_icon.svg",
  userIcon:"/assets/images/user_icon.svg",
  clinetimgon:"/assets/images/clinetimg001.png",
  clinetimgtw:"/assets/images/clinetimg002.png",
  clinetimgth:"/assets/images/clinetimg003.png",
  startimgfeed:"/assets/images/startimgwrap01.png",
  abtIco1: "/assets/images/aboutico1.svg",
  abtIco2: "/assets/images/aboutico2.svg",
  abtIco3: "/assets/images/aboutico3.svg",
  playIcon:"/assets/images/play_icon.svg",
  GoogleIcon:"/assets/images/google_icon.png",
  AppleIcon:"/assets/images/apple_icon.png",
  bannerImage:"/assets/images/banner_image.png",
  sliderarwson:"/assets/images/arws01.svg",
  sliderarwstw:"/assets/images/arws02.svg",
  featureimgicn:"/assets/images/fetricnimg01.svg",
  featuremainimg:"/assets/images/fetrmanicn03.png",
  keyIco1:"/assets/images/keyico1.svg",
  keyIco2:"/assets/images/keyico2.svg",
  keyIco3:"/assets/images/keyico3.svg",
  keyIco4:"/assets/images/keyico4.svg",
  crossIco:"/assets/images/cross.svg",
  tickIco:"/assets/images/tick.svg",
  dropdnmenuicn1:"/assets/images/menudropdnicn01.svg",
  dropdnmenuicn2:"/assets/images/menudropdnicn02.svg",
  dropdnmenuicn3:"/assets/images/menudropdnicn03.svg",
  dropdnmenuicn4:"/assets/images/menudropdnicn04.svg",
  dropdnmenuicn5:"/assets/images/menudropdnicn05.svg",
  dropdnmenuicn6:"/assets/images/menudropdnicn06.svg",
  bloglistimg1:"/assets/images/blogimg01.jpg",
  bloglistimg2:"/assets/images/blogimg02.jpg",
  bloglistimg3:"/assets/images/blogimg03.jpg",
  bloglistimg4:"/assets/images/blogimg04.jpg",
  bloglistimg5:"/assets/images/blogimg05.jpg",
  bloglistimg6:"/assets/images/blogimg06.jpg",
  bloglistimg7:"/assets/images/blogimg07.jpg",
  bloglistimg8:"/assets/images/blogimg08.jpg",
  bloglistimg9:"/assets/images/blogimg09.jpg",
  bloglistimg10:"/assets/images/blogimg10.jpg",
  bloglistimg11:"/assets/images/blogimg11.jpg",
  bloglistimg12:"/assets/images/blogimg12.jpg",
  blogawrsicn:"/assets/images/blogawrs01.svg",
  singleBlogimg:"/assets/images/singleBlogimg01.jpg",
  fileIcon:"/assets/images/file_icon.svg",
  emnailinpticn:"/assets/images/emailicn01.svg",
  passwrdicninpt:"/assets/images/passwrdicninpt01.svg",
  usericniptfld:"/assets/images/usericninput01.svg",
  callinpticnimg:"/assets/images/callimginpt01.svg",
  companyicnimg:"/assets/images/compannmicn01.svg",
  companyicnaddres:"/assets/images/addresicninpt01.svg",
  cityicninpt:"/assets/images/cityicninput01.svg",
  zipcodeicnipnt:"/assets/images/zipcodeinpticn01.svg",
  refralcodeicninpt:"/assets/images/referalcodeicninp01.svg",
  countryicnipt:"/assets/images/countryicnipt01.svg",
  downarwrsinpt:"/assets/images/dwnarrwsicn03.svg",
  stateicninpt:"/assets/images/stateicninpt01.svg",
  videoiconpopup:"/assets/images/videoicnPopup01.svg",
  msgicninput:"/assets/images/msgicninpt01.svg",
  contcticonmn1:"/assets/images/contctcallicn03.svg",
  contcticonmn2:"/assets/images/contactlocincmn03.svg",
  contcticonmn3:"/assets/images/contactimeicnmn03.svg",
  passshowicon:"/assets/images/passshowicon03.svg",
  checkBoxcusmBx:"/assets/images/checkBoxcustombx03.svg",
  checkBoxcusmBx2:"/assets/images/checkBoxcustombx09.svg",
  hamMenuIcon:"/assets/images/ham_menu_icon.png",
  dwarwsslect:"/assets/images/dnarwslectnewar01.svg",
  modalsigninicon:"/assets/images/modaliconsignin.svg",
  modalcloseicn:"/assets/images/modalcloseicn03.svg",
  lineimglineLogin:"/assets/images/lineigline01.svg",
  closeiconmnmenu:"/assets/images/closeiconmni325.svg",
  scrolltobtn:"/assets/images/up-arrow.png",
  demotabimg2:"/assets/images/demotab2.png",
  demotabimg3:"/assets/images/demotab3.png",
  arrowdownimg: "/assets/images/arrow-down.png",
  tabImage: "/assets/images/tab_image.png",
  video1: "/assets/images/video.mp4",
};




